version: 2.0
jobs:
  build:
    docker:
      - image: base/devel:latest
    steps:
      - run: 
          name: Update Pacman
          command: 'pacman -Syu --noconfirm'
      - run: 
          name: Install Git
          command: 'pacman -S git --noconfirm'
      - run: 
          name: Create windscribe User and Add to Wheel Group
          command: 'useradd -m -g wheel -s /bin/bash windscribe'
      - run: 
          name: Give Wheel Group sudoers Permission
          command: "sed -i '85s/.*/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers"
      - run:
          name: Checkout Code from GitHub
          command: 'su - windscribe -c "git clone https://github.com/hkuchampudi/Windscribe.git"'
      - run: 
          name: Build PKGBUILD as windscribe User
          command: 'su - windscribe -c "cd ~/Windscribe && makepkg -cs PKGBUILD --noconfirm"'
      - run: 
          name: Install Built Windscribe Package
          command: 'su - windscribe -c "cd ~/Windscribe && sudo pacman -U *.pkg.tar.xz --noconfirm"'
      ## Start tests
      - run: 
          name: Start Windscribe Service
          command: '/usr/bin/windscribe start'
      - run: 
          name: Check if Windscribe is Running
          command: 'if windscribe status | grep -q "status: running"; then echo "SUCCESS"; else exit 1; fi'
      - run: 
          name: Check if Windscribe can Connect
          command: 'if windscribe connect | grep -q "Please login to use Windscribe"; then echo "SUCCESS"; else exit 1; fi'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
